### ISSUE TITLE
Apply for open source status on Zulip

### ISSUE THREAD

**Issue by samjrholt** [MaMMoS-project/management#8]

**Comment by fangohr** [comment]
We should add an 'acknowledgement' to zulip before applying for sponsorship (see: https://zulip.com/help/linking-to-zulip-website).

**Comment by fangohr** [comment]
I have applied for the Zulip sponsorship for Open source projects, and it [has been approved](https://mammos.zulipchat.com/#narrow/dm/100006,600546-dm/near/460076411) - thank you Zulip!
